
CREATE TABLE IF NOT EXISTS `#__mdtickets_items` (
  `mdtickets_item_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `prio` varchar(255) NOT NULL,
  `category` varchar(255) NOT NULL DEFAULT '',
  `short` varchar(255) NOT NULL DEFAULT '',
  `detail` mediumtext NOT NULL,
  `requester` varchar(255) NOT NULL DEFAULT '',
  `deadline` date,
  `assigned` varchar(255) DEFAULT '',
  `start_date` date,
  `itoncall` varchar(55) DEFAULT NULL,
  `started` tinyint(3) NOT NULL DEFAULT 0,
  `published` tinyint(3) NOT NULL DEFAULT 1,
  `status` varchar(255) DEFAULT '',
  `token` char(32) DEFAULT NULL,
  `created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` bigint(20) NOT NULL DEFAULT '0',
  `modified_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` bigint(20) NOT NULL DEFAULT '0',
  `locked_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `locked_by` bigint(20) NOT NULL DEFAULT '0',
  `completion_date` date DEFAULT NULL,
  `completed_by` varchar(255),
  `remark` mediumtext NOT NULL,
  `actie` varchar(255) DEFAULT '',
  `periodtime` varchar(255) DEFAULT '',
  PRIMARY KEY (`mdtickets_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `#__mdtickets_lastlogins` (
  `mdtickets_lastlogin_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `lastlogin` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `previouslogin` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `published` tinyint(3) NOT NULL DEFAULT 1,
  `token` char(32) DEFAULT NULL,
  `created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` bigint(20) NOT NULL DEFAULT '0',
  `modified_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` bigint(20) NOT NULL DEFAULT '0',
  `locked_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `locked_by` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`mdtickets_lastlogin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `#__mdtickets_computers` (
  `mdtickets_computer_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `computername` varchar(255) NOT NULL,
  `computerdesc` varchar(255) NOT NULL,
  `computersn` varchar(255) NOT NULL,
  `type` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `bought_at` varchar(255) NOT NULL,
  `windows` varchar(255) NOT NULL,
  `windows_sn` varchar(255) NOT NULL,
  `office` varchar(255) NOT NULL,
  `office_sn` varchar(255) NOT NULL,
  `software1` varchar(255) NOT NULL,
  `software1_sn` varchar(255) NOT NULL,
  `software2` varchar(255) NOT NULL,
  `software2_sn` varchar(255) NOT NULL,
  `software3` varchar(255) NOT NULL,
  `software3_sn` varchar(255) NOT NULL,
  `software4` varchar(255) NOT NULL,
  `software4_sn` varchar(255) NOT NULL,
  `bought_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `remark` mediumtext NOT NULL,
  `published` tinyint(3) NOT NULL DEFAULT 1,
  `token` char(32) DEFAULT NULL,
  `created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` bigint(20) NOT NULL DEFAULT '0',
  `modified_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` bigint(20) NOT NULL DEFAULT '0',
  `locked_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `locked_by` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`mdtickets_computer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `#__mdtickets_phones` (
  `mdtickets_phone_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `phone_number` varchar(255) NOT NULL,
  `provider` varchar(255) NOT NULL,
  `contract` varchar(255) NOT NULL,
  `sim_number` varchar(255) NOT NULL,
  `phone_brand1` varchar(255) NOT NULL,
  `phone_type1` varchar(255) NOT NULL,
  `phone_sn1` varchar(255) NOT NULL,
  `phone_in_use1` tinyint(3) NOT NULL DEFAULT 0,
  `phone_bought_date1` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `phone_shop1` varchar(255) NOT NULL,
  `phone_brand2` varchar(255) NOT NULL,
  `phone_type2` varchar(255) NOT NULL,
  `phone_sn2` varchar(255) NOT NULL,
  `phone_in_use2` tinyint(3) NOT NULL DEFAULT 0,
  `phone_bought_date2` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `phone_shop2` varchar(255) NOT NULL,
  `phone_brand3` varchar(255) NOT NULL,
  `phone_type3` varchar(255) NOT NULL,
  `phone_sn3` varchar(255) NOT NULL,
  `phone_in_use3` tinyint(3) NOT NULL DEFAULT 0,
  `phone_bought_date3` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `phone_shop3` varchar(255) NOT NULL,
  `phone_brand4` varchar(255) NOT NULL,
  `phone_type4` varchar(255) NOT NULL,
  `phone_sn4` varchar(255) NOT NULL,
  `phone_in_use4` tinyint(3) NOT NULL DEFAULT 0,
  `phone_bought_date4` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `phone_shop4` varchar(255) NOT NULL,
  `data_national` varchar(255) NOT NULL,
  `data_int` varchar(255) NOT NULL,
  `contract_end_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `remark` mediumtext NOT NULL,
  `double_sim` tinyint(3) NOT NULL DEFAULT 0,
  `published` tinyint(3) NOT NULL DEFAULT 1,
  `token` char(32) DEFAULT NULL,
  `created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` bigint(20) NOT NULL DEFAULT '0',
  `modified_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` bigint(20) NOT NULL DEFAULT '0',
  `locked_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `locked_by` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`mdtickets_phone_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `#__mdtickets_users` (
`mdtickets_user_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
`username` varchar(255) NOT NULL,
`shortname` varchar(255) NOT NULL,
`phonenr` varchar(255) NOT NULL,
`phone_internal` varchar(255) NOT NULL,
`skype` varchar(255) NOT NULL,
`email` varchar(255) NOT NULL,
`username_host` varchar(255) NOT NULL,
`country` varchar(255) NOT NULL,
`left_host` tinyint(3) NOT NULL DEFAULT 0,
`end_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
`remark` mediumtext NOT NULL,
`published` tinyint(3) NOT NULL DEFAULT 1,
`token` char(32) DEFAULT NULL,
`created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
`created_by` bigint(20) NOT NULL DEFAULT '0',
`modified_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
`modified_by` bigint(20) NOT NULL DEFAULT '0',
`locked_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
`locked_by` bigint(20) NOT NULL DEFAULT '0',
PRIMARY KEY (`mdtickets_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;