
CREATE TABLE IF NOT EXISTS `#__mdtickets_items` (
  `mdtickets_item_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `prio` varchar(255) NOT NULL,
  `category` varchar(255) NOT NULL DEFAULT '',
  `short` varchar(255) NOT NULL DEFAULT '',
  `detail` mediumtext NOT NULL,
  `requester` varchar(255) NOT NULL DEFAULT '',
  `deadline` date,
  `assigned` varchar(255) DEFAULT '',
  `start_date` date,
  `itoncall` varchar(55) DEFAULT NULL,
  `started` tinyint(3) NOT NULL DEFAULT 0,
  `published` tinyint(3) NOT NULL DEFAULT 1,
  `status` varchar(255) DEFAULT '',
  `token` char(32) DEFAULT NULL,
  `created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` bigint(20) NOT NULL DEFAULT '0',
  `modified_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` bigint(20) NOT NULL DEFAULT '0',
  `locked_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `locked_by` bigint(20) NOT NULL DEFAULT '0',
  `completion_date` date DEFAULT NULL,
  `completed_by` varchar(255),
  `remark` mediumtext NOT NULL,
  `actie` varchar(255) DEFAULT '',
  `periodtime` varchar(255) DEFAULT '',
  PRIMARY KEY (`mdtickets_item_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `#__mdtickets_lastlogins` (
  `mdtickets_lastlogin_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `lastlogin` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `previouslogin` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `published` tinyint(3) NOT NULL DEFAULT 1,
  `token` char(32) DEFAULT NULL,
  `created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` bigint(20) NOT NULL DEFAULT '0',
  `modified_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` bigint(20) NOT NULL DEFAULT '0',
  `locked_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `locked_by` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`mdtickets_lastlogin_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `#__mdtickets_computers` (
  `mdtickets_computer_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) DEFAULT NULL,
  `computername` varchar(255) NOT NULL,
  `computerdesc` varchar(255) NOT NULL,
  `computersn` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `bought_at` varchar(255) NOT NULL,
  `windows` varchar(255) NOT NULL,
  `windows_sn` varchar(255) NOT NULL,
  `office` varchar(255) NOT NULL,
  `office_sn` varchar(255) NOT NULL,
  `software1` varchar(255) NOT NULL,
  `software1_sn` varchar(255) NOT NULL,
  `software2` varchar(255) NOT NULL,
  `software2_sn` varchar(255) NOT NULL,
  `software3` varchar(255) NOT NULL,
  `software3_sn` varchar(255) NOT NULL,
  `software4` varchar(255) NOT NULL,
  `software4_sn` varchar(255) NOT NULL,
  `bought_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `remark` mediumtext NOT NULL,
  `published` tinyint(3) NOT NULL DEFAULT 1,
  `token` char(32) DEFAULT NULL,
  `created_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `created_by` bigint(20) NOT NULL DEFAULT '0',
  `modified_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `modified_by` bigint(20) NOT NULL DEFAULT '0',
  `locked_on` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `locked_by` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`mdtickets_computer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;